### ISSUE TITLE
IE11: Säilytysyksiköt | Tulosta nimiöt: Ei tulostu, tulee virheilmoitus

### ISSUE THREAD

**Issue by minna-aaltonen** [Proactum/ARTI#197]
**Tätä virhettä ei tule Firefox selaimella**

Yritin tulostaa nimiöt säilytysyksiköille: 10 000 - 10 003

-> Virheilmoitus:

SyntaxError: Unexpected token u
    at Object.parse (native)
    at Object.module.exports [as nimiö] (/opt/arti/20150505/node_modules/arti/node_modules/excel-export/nimiö.jsx:120:20)
    at module.exports (/opt/arti/20150505/node_modules/arti/node_modules/excel-export/writer.jsx:26:11)
    at Layer.handle [as handle_request] (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/layer.js:82:5)
    at next (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/layer.js:82:5)
    at /opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/index.js:267:22
    at param (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/index.js:340:14)
    at param (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/index.js:400:3)
    at next (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/index.js:261:10)
    at Layer.handle [as handle_request] (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/layer.js:78:12)
    at trim_prefix (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/index.js:302:13)
    at /opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/opt/arti/20150505/node_modules/arti/node_modules/express/lib/router/index.js:321:12)

**Comment by mustakostaja** [comment]
J

**Comment by minna-aaltonen** [comment]
Nyt nimiö tulostuu myös IE11 selaimesta.
